import { Job, Candidate, HumanReview, AuditLog, Plan } from '@/types';

export const INITIAL_JOBS: Job[] = [
  {
    id: 'vaga-01',
    title: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    area: 'Frontend',
    level: 'Sênior',
    minExperienceYears: 5,
    description: 'Buscamos desenvolvedor Frontend Sênior com sólida experiência no ecossistema React, Next.js (App Router), TypeScript e arquitetura de componentes escaláveis.',
    skills: [
      { id: 'sk-1', name: 'React', weight: 30, required: true },
      { id: 'sk-2', name: 'Next.js', weight: 25, required: true },
      { id: 'sk-3', name: 'TypeScript', weight: 20, required: true },
      { id: 'sk-4', name: 'Tailwind CSS', weight: 15, required: false },
      { id: 'sk-5', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'vaga-02',
    title: 'Engenheiro Backend Node.js Pleno',
    area: 'Backend',
    level: 'Pleno',
    minExperienceYears: 3,
    description: 'Responsável por projetar e desenvolver APIs RESTful e GraphQL de alto desempenho, modelagem de banco de dados relacional e integração com mensageria.',
    skills: [
      { id: 'sk-6', name: 'Node.js', weight: 30, required: true },
      { id: 'sk-7', name: 'TypeScript', weight: 25, required: true },
      { id: 'sk-8', name: 'SQL', weight: 20, required: true },
      { id: 'sk-9', name: 'Docker', weight: 15, required: false },
      { id: 'sk-10', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-18T14:30:00Z',
    updatedAt: '2026-08-18T14:30:00Z',
  },
  {
    id: 'vaga-03',
    title: 'Engenheiro de Dados Pleno (Python / Spark / SQL)',
    area: 'Data & Analytics',
    level: 'Pleno',
    minExperienceYears: 3,
    description: 'Atuação na construção de pipelines de dados ETL/ELT robustos, estruturação de data lakes e garantia de qualidade de dados.',
    skills: [
      { id: 'sk-11', name: 'Python', weight: 30, required: true },
      { id: 'sk-12', name: 'SQL', weight: 25, required: true },
      { id: 'sk-13', name: 'Spark', weight: 20, required: true },
      { id: 'sk-14', name: 'Airflow', weight: 15, required: false },
      { id: 'sk-15', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-20T09:15:00Z',
    updatedAt: '2026-08-20T09:15:00Z',
  },
  {
    id: 'vaga-04',
    title: 'Especialista DevOps / Cloud (Kubernetes & AWS)',
    area: 'DevOps / Cloud',
    level: 'Especialista',
    minExperienceYears: 6,
    description: 'Liderança técnica na infraestrutura cloud, automação de esteiras CI/CD, monitoramento e observabilidade, e governança de clusters Kubernetes.',
    skills: [
      { id: 'sk-16', name: 'Kubernetes', weight: 30, required: true },
      { id: 'sk-17', name: 'Docker', weight: 25, required: true },
      { id: 'sk-18', name: 'Terraform', weight: 20, required: true },
      { id: 'sk-19', name: 'AWS', weight: 15, required: false },
      { id: 'sk-20', name: 'CI/CD', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-22T11:00:00Z',
    updatedAt: '2026-08-22T11:00:00Z',
  },
  {
    id: 'vaga-05',
    title: 'Desenvolvedor Full Stack Júnior (Web)',
    area: 'Full Stack',
    level: 'Júnior',
    minExperienceYears: 1,
    description: 'Oportunidade para profissionais em início de carreira para atuar no desenvolvimento de telas e integração com APIs na plataforma web da empresa.',
    skills: [
      { id: 'sk-21', name: 'JavaScript', weight: 35, required: true },
      { id: 'sk-22', name: 'React', weight: 25, required: true },
      { id: 'sk-23', name: 'Node.js', weight: 20, required: true },
      { id: 'sk-24', name: 'SQL', weight: 10, required: false },
      { id: 'sk-25', name: 'Git', weight: 10, required: false },
    ],
    status: 'ativa',
    createdAt: '2026-08-25T16:45:00Z',
    updatedAt: '2026-08-25T16:45:00Z',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-01',
    name: 'Lucas Andrade',
    email: 'l***e@email.com',
    phone: '(11) 9****-1234',
    experienceYears: 6,
    level: 'Sênior',
    technicalSkills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Git', 'Docker', 'GraphQL'],
    bio: 'Desenvolvedor Frontend Sênior com experiência em design systems, Server Components e Next.js.',
    resumeFileName: 'curriculo_lucas_andrade.pdf',
    resumeFileSize: 1420500,
    resumeUploadedAt: '2026-08-26T08:30:00Z',
    hasResume: true,
    createdAt: '2026-08-26T08:30:00Z',
    updatedAt: '2026-08-26T08:30:00Z',
  },
  {
    id: 'cand-02',
    name: 'Mariana Costa',
    email: 'm***a@email.com',
    phone: '(21) 9****-5678',
    experienceYears: 4,
    level: 'Pleno',
    technicalSkills: ['React', 'Next.js', 'TypeScript', 'Git', 'JavaScript', 'CSS3'],
    bio: 'Desenvolvedora Frontend com foco em interfaces acessíveis e responsivas.',
    resumeFileName: 'curriculo_mariana_costa.pdf',
    resumeFileSize: 980400,
    resumeUploadedAt: '2026-08-26T09:10:00Z',
    hasResume: true,
    createdAt: '2026-08-26T09:10:00Z',
    updatedAt: '2026-08-26T09:10:00Z',
  },
  {
    id: 'cand-03',
    name: 'Rodrigo Silveira',
    email: 'r***a@email.com',
    phone: '(31) 9****-9012',
    experienceYears: 3,
    level: 'Pleno',
    technicalSkills: ['React', 'TypeScript', 'Git', 'JavaScript', 'HTML5'],
    bio: 'Desenvolvedor Frontend focado em SPAs e integração de serviços.',
    resumeFileName: 'curriculo_rodrigo_silveira.pdf',
    resumeFileSize: 850200,
    resumeUploadedAt: '2026-08-26T10:05:00Z',
    hasResume: true,
    createdAt: '2026-08-26T10:05:00Z',
    updatedAt: '2026-08-26T10:05:00Z',
  },
  {
    id: 'cand-04',
    name: 'Camila Duarte',
    email: 'c***e@email.com',
    phone: '(41) 9****-3456',
    experienceYears: 2,
    level: 'Júnior',
    technicalSkills: ['JavaScript', 'HTML5', 'CSS3', 'Git', 'React'],
    bio: 'Desenvolvedora Web júnior com projetos em React e JavaScript vanilla.',
    resumeFileName: 'curriculo_camila_duarte.pdf',
    resumeFileSize: 720000,
    resumeUploadedAt: '2026-08-26T11:20:00Z',
    hasResume: true,
    createdAt: '2026-08-26T11:20:00Z',
    updatedAt: '2026-08-26T11:20:00Z',
  },
  {
    id: 'cand-05',
    name: 'Felipe Alcântara',
    email: 'f***a@email.com',
    phone: '(51) 9****-7890',
    experienceYears: 4,
    level: 'Pleno',
    technicalSkills: ['Node.js', 'TypeScript', 'SQL', 'Docker', 'Git', 'PostgreSQL', 'Express'],
    bio: 'Backend Engineer com foco em APIs resilientes, microserviços e bancos SQL.',
    resumeFileName: 'curriculo_felipe_alcantara.pdf',
    resumeFileSize: 1100300,
    resumeUploadedAt: '2026-08-27T08:00:00Z',
    hasResume: true,
    createdAt: '2026-08-27T08:00:00Z',
    updatedAt: '2026-08-27T08:00:00Z',
  },
  {
    id: 'cand-06',
    name: 'Beatriz Mendes',
    email: 'b***s@email.com',
    phone: '(61) 9****-2345',
    experienceYears: 3,
    level: 'Pleno',
    technicalSkills: ['Node.js', 'TypeScript', 'SQL', 'Git', 'REST'],
    bio: 'Desenvolvedora Backend Node.js atuando com arquitetura REST e testes automatizados.',
    resumeFileName: 'curriculo_beatriz_mendes.pdf',
    resumeFileSize: 890000,
    resumeUploadedAt: '2026-08-27T09:40:00Z',
    hasResume: true,
    createdAt: '2026-08-27T09:40:00Z',
    updatedAt: '2026-08-27T09:40:00Z',
  },
  {
    id: 'cand-07',
    name: 'Gabriel Rocha',
    email: 'g***a@email.com',
    phone: '(71) 9****-6789',
    experienceYears: 2,
    level: 'Júnior',
    technicalSkills: ['Node.js', 'JavaScript', 'SQL', 'Git'],
    bio: 'Desenvolvedor backend júnior com foco em banco de dados e APIs em Node.',
    resumeFileName: 'curriculo_gabriel_rocha.pdf',
    resumeFileSize: 650000,
    resumeUploadedAt: '2026-08-27T10:15:00Z',
    hasResume: true,
    createdAt: '2026-08-27T10:15:00Z',
    updatedAt: '2026-08-27T10:15:00Z',
  },
  {
    id: 'cand-08',
    name: 'Larissa Ramos',
    email: 'l***s@email.com',
    phone: '(81) 9****-0123',
    experienceYears: 5,
    level: 'Sênior',
    technicalSkills: ['Python', 'SQL', 'Spark', 'Airflow', 'Git', 'AWS', 'Data Modeling'],
    bio: 'Engenheira de dados especializada em processamento distribuído com PySpark e orquestração Airflow.',
    resumeFileName: 'curriculo_larissa_ramos.pdf',
    resumeFileSize: 1350000,
    resumeUploadedAt: '2026-08-28T09:00:00Z',
    hasResume: true,
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'cand-09',
    name: 'Thiago Neves',
    email: 't***s@email.com',
    phone: '(19) 9****-4567',
    experienceYears: 7,
    level: 'Especialista',
    technicalSkills: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'CI/CD', 'Linux', 'Ansible'],
    bio: 'Especialista Cloud & DevOps focado em infraestrutura declarativa e resiliência de clusters.',
    resumeFileName: 'curriculo_thiago_neves.pdf',
    resumeFileSize: 1600000,
    resumeUploadedAt: '2026-08-28T10:30:00Z',
    hasResume: true,
    createdAt: '2026-08-28T10:30:00Z',
    updatedAt: '2026-08-28T10:30:00Z',
  },
  {
    id: 'cand-10',
    name: 'Juliana Peixoto',
    email: 'j***o@email.com',
    phone: '(85) 9****-8901',
    experienceYears: 1,
    level: 'Júnior',
    technicalSkills: ['JavaScript', 'React', 'Node.js', 'Git', 'HTML5', 'CSS3'],
    bio: 'Desenvolvedora Full Stack iniciante apaixonada por React e Node.js.',
    resumeFileName: 'curriculo_juliana_peixoto.pdf',
    resumeFileSize: 740000,
    resumeUploadedAt: '2026-08-29T14:00:00Z',
    hasResume: true,
    createdAt: '2026-08-29T14:00:00Z',
    updatedAt: '2026-08-29T14:00:00Z',
  },
  {
    id: 'cand-11',
    name: 'Diego Martins',
    email: 'd***s@email.com',
    phone: '(48) 9****-2345',
    experienceYears: 5,
    level: 'Sênior',
    technicalSkills: ['Java', 'Spring Boot', 'Oracle DB', 'Kafka', 'Microservices'],
    bio: 'Desenvolvedor Java/Spring enterprise com sólida base em sistemas bancários.',
    resumeFileName: 'curriculo_diego_martins.pdf',
    resumeFileSize: 920000,
    resumeUploadedAt: '2026-08-29T15:20:00Z',
    hasResume: true,
    createdAt: '2026-08-29T15:20:00Z',
    updatedAt: '2026-08-29T15:20:00Z',
  },
  {
    id: 'cand-12',
    name: 'Carolina Farias (Teste Incompleto)',
    email: 'c***s@email.com',
    phone: '(11) 9****-9999',
    experienceYears: 0,
    level: 'Estágio',
    technicalSkills: [], // Dados incompletos para testar RG06 e RG07
    bio: 'Estudante de Ciência da Computação iniciando carreira.',
    hasResume: false,
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  }
];

export const INITIAL_REVIEWS: HumanReview[] = [
  {
    id: 'rev-01',
    jobId: 'vaga-01',
    candidateId: 'cand-01',
    candidateName: 'Lucas Andrade',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    score: 100,
    status: 'Aprovado para próxima etapa',
    reviewerName: 'Ana Paula Recrutadora',
    reviewerRole: 'Recrutador',
    notes: 'Candidato com 100% de matching técnico. Experiência de 6 anos excede os 5 anos requeridos. Currículo demonstra excelente domínio em Next.js App Router.',
    technicalFeedback: 'Aprovado para entrevista técnica com o Tech Lead.',
    reviewedAt: '2026-08-26T14:30:00Z',
    createdAt: '2026-08-26T14:30:00Z',
    updatedAt: '2026-08-26T14:30:00Z',
  },
  {
    id: 'rev-02',
    jobId: 'vaga-01',
    candidateId: 'cand-02',
    candidateName: 'Mariana Costa',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    score: 85,
    status: 'Revisado',
    reviewerName: 'Ana Paula Recrutadora',
    reviewerRole: 'Recrutador',
    notes: 'Boa compatibilidade técnica (85%). Faltou Tailwind CSS no perfil explícito, porém tem sólido conhecimento em Next e TypeScript. Nível Pleno vs Sênior exigido.',
    technicalFeedback: 'Manter no radar para alinhamento de expectativas de senioridade.',
    reviewedAt: '2026-08-26T15:00:00Z',
    createdAt: '2026-08-26T15:00:00Z',
    updatedAt: '2026-08-26T15:00:00Z',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    action: 'JOB_CREATED',
    timestamp: '2026-08-15T10:00:00Z',
    jobId: 'vaga-01',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    weightsUsed: { 'React': 30, 'Next.js': 25, 'TypeScript': 20, 'Tailwind CSS': 15, 'Git': 10 },
    actor: { name: 'Ana Paula Recrutadora', role: 'Recrutador' },
    details: 'Vaga cadastrada com 5 competências técnicas configuradas totalizando 100% de peso.',
    immutableHash: 'a1b2c3d4e5f67890123456789abcdef012345678'
  },
  {
    id: 'aud-02',
    action: 'MATCHING_CALCULATED',
    timestamp: '2026-08-26T08:35:00Z',
    jobId: 'vaga-01',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    candidateId: 'cand-01',
    candidateName: 'Lucas Andrade',
    score: 100,
    classification: 'ALTA',
    matchedSkills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Git'],
    missingSkills: [],
    weightsUsed: { 'React': 30, 'Next.js': 25, 'TypeScript': 20, 'Tailwind CSS': 15, 'Git': 10 },
    actor: { name: 'Sistema IT Matcher', role: 'Sistema' },
    details: 'Cálculo de Smart Matching executado. Score: 100% (Alta compatibilidade).',
    immutableHash: 'f0e9d8c7b6a543210987654321fedcba09876543'
  },
  {
    id: 'aud-03',
    action: 'REVIEW_UPDATED',
    timestamp: '2026-08-26T14:30:00Z',
    jobId: 'vaga-01',
    jobTitle: 'Desenvolvedor Frontend Sênior (Next.js/React)',
    candidateId: 'cand-01',
    candidateName: 'Lucas Andrade',
    score: 100,
    classification: 'ALTA',
    previousStatus: 'Pendente de revisão',
    newStatus: 'Aprovado para próxima etapa',
    actor: { name: 'Ana Paula Recrutadora', role: 'Recrutador' },
    details: 'Revisão humana realizada. Status atualizado para "Aprovado para próxima etapa". Decisão humana registrada com sucesso.',
    immutableHash: '11223344556677889900aabbccddeeff11223344'
  }
];

export const INITIAL_PARTNER_COMPANIES = [
  {
    id: 'emp_tech_01',
    name: 'Tech Solutions Digital',
    email: 'empresa@techsolutions.com.br',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'Tech Solutions Digital',
    companyData: {
      id: 'emp_tech_01',
      name: 'Tech Solutions Digital',
      cnpj: '12.345.678/0001-90',
      email: 'empresa@techsolutions.com.br',
      phone: '(11) 3456-7890',
      contactName: 'Carlos Eduardo (Head de Engenharia)',
      companyType: 'Empresa de Tecnologia',
      companyIndustry: 'Desenvolvimento de Software',
      segment: 'Software & Engenharia Web',
      companySize: '51–200 funcionários',
      city: 'São Paulo',
      state: 'SP',
      country: 'Brasil',
      website: 'https://techsolutions.com.br',
      description: 'Líder em engenharia de software escalável, arquitetura de microsserviços e plataformas digitais de alta disponibilidade.',
      logo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80',
      jobsCount: 5,
      candidatesCount: 38,
      partnershipStatus: 'Parceiro Premium',
      createdAt: '2026-01-15T09:00:00Z',
    }
  },
  {
    id: 'emp_fintech_02',
    name: 'FinTech Brasil Hub',
    email: 'talentos@fintechbrasil.com.br',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'FinTech Brasil Hub',
    companyData: {
      id: 'emp_fintech_02',
      name: 'FinTech Brasil Hub',
      cnpj: '23.456.789/0001-01',
      email: 'talentos@fintechbrasil.com.br',
      phone: '(11) 4002-8922',
      contactName: 'Mariana Pires (Tech Recruiter)',
      companyType: 'Fintech & Instituição Financeira',
      companyIndustry: 'Serviços Financeiros / Banking',
      segment: 'Fintech & Open Finance',
      companySize: '500+ funcionários',
      city: 'São Paulo',
      state: 'SP',
      country: 'Brasil',
      website: 'https://fintechbrasil.com.br',
      description: 'Inovação bancária e pagamentos instantâneos com infraestrutura ultra-segura e APIs de Open Finance.',
      logo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=120&auto=format&fit=crop&q=80',
      jobsCount: 8,
      candidatesCount: 64,
      partnershipStatus: 'Parceiro Premium',
      createdAt: '2026-02-20T14:30:00Z',
    }
  },
  {
    id: 'emp_omnicloud_03',
    name: 'OmniCloud Enterprise',
    email: 'parcerias@omnicloud.io',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'OmniCloud Enterprise',
    companyData: {
      id: 'emp_omnicloud_03',
      name: 'OmniCloud Enterprise',
      cnpj: '34.567.890/0001-12',
      email: 'parcerias@omnicloud.io',
      phone: '(19) 3210-9876',
      contactName: 'Roberto Albuquerque (VP de Operações)',
      companyType: 'Cloud & Infraestrutura',
      companyIndustry: 'Computação em Nuvem / DevOps',
      segment: 'Cloud & DevOps Solutions',
      companySize: '201–500 funcionários',
      city: 'Campinas',
      state: 'SP',
      country: 'Brasil',
      website: 'https://omnicloud.io',
      description: 'Especialista em governança multi-cloud, orquestração Kubernetes e automação contínua de esteiras CI/CD.',
      logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
      jobsCount: 4,
      candidatesCount: 29,
      partnershipStatus: 'Ativa',
      createdAt: '2026-03-12T11:00:00Z',
    }
  },
  {
    id: 'emp_datasphere_04',
    name: 'DataSphere Analytics & AI',
    email: 'carreiras@datasphere.ai',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'DataSphere Analytics & AI',
    companyData: {
      id: 'emp_datasphere_04',
      name: 'DataSphere Analytics & AI',
      cnpj: '45.678.901/0001-23',
      email: 'carreiras@datasphere.ai',
      phone: '(31) 3344-5566',
      contactName: 'Luciana Ferreira (Head de IA & Dados)',
      companyType: 'Inteligência Artificial & Big Data',
      companyIndustry: 'Data Science & Machine Learning',
      segment: 'Inteligência Artificial & Dados',
      companySize: '51–200 funcionários',
      city: 'Belo Horizonte',
      state: 'MG',
      country: 'Brasil',
      website: 'https://datasphere.ai',
      description: 'Pesquisa avançada e aplicação de modelos de Machine Learning, LLMs e orquestração de Data Lakes industriais.',
      logo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=120&auto=format&fit=crop&q=80',
      jobsCount: 6,
      candidatesCount: 45,
      partnershipStatus: 'Estratégico',
      createdAt: '2026-04-05T16:20:00Z',
    }
  },
  {
    id: 'emp_veloce_05',
    name: 'Veloce E-Commerce Global',
    email: 'rh@velocecommerce.com',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'Veloce E-Commerce Global',
    companyData: {
      id: 'emp_veloce_05',
      name: 'Veloce E-Commerce Global',
      cnpj: '56.789.012/0001-34',
      email: 'rh@velocecommerce.com',
      phone: '(41) 3088-7711',
      contactName: 'Danilo Ramos (Gerente de Gente & Gestão)',
      companyType: 'Varejo Digital & E-Commerce',
      companyIndustry: 'Comércio Eletrônico & Marketplace',
      segment: 'E-commerce & Retail Tech',
      companySize: '500+ funcionários',
      city: 'Curitiba',
      state: 'PR',
      country: 'Brasil',
      website: 'https://velocecommerce.com',
      description: 'Ecossistema omnicanal de e-commerce transacionando milhões de pedidos mensais com arquitetura serverless.',
      logo: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=120&auto=format&fit=crop&q=80',
      jobsCount: 3,
      candidatesCount: 22,
      partnershipStatus: 'Ativa',
      createdAt: '2026-05-18T10:15:00Z',
    }
  },
  {
    id: 'emp_healthtech_06',
    name: 'HealthTech Integrada',
    email: 'contato@healthtechintegrada.med.br',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'HealthTech Integrada',
    companyData: {
      id: 'emp_healthtech_06',
      name: 'HealthTech Integrada',
      cnpj: '67.890.123/0001-45',
      email: 'contato@healthtechintegrada.med.br',
      phone: '(51) 3288-4400',
      contactName: 'Dra. Vanessa Martins (Diretora de Inovação Médica)',
      companyType: 'Saúde Digital & Telemedicina',
      companyIndustry: 'HealthTech / Biotecnologia',
      segment: 'Saúde Digital & HealthTech',
      companySize: '51–200 funcionários',
      city: 'Porto Alegre',
      state: 'RS',
      country: 'Brasil',
      website: 'https://healthtechintegrada.med.br',
      description: 'Plataforma integrada de prontuário eletrônico interoperável, telemedicina segura e teleconsultas com conformidade HIPAA e LGPD.',
      logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=120&auto=format&fit=crop&q=80',
      jobsCount: 2,
      candidatesCount: 16,
      partnershipStatus: 'Em Homologação',
      createdAt: '2026-06-28T13:40:00Z',
    }
  },
  {
    id: 'emp_cybershield_07',
    name: 'CyberShield Segurança Digital',
    email: 'soc@cybershield.security',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'CyberShield Segurança Digital',
    companyData: {
      id: 'emp_cybershield_07',
      name: 'CyberShield Segurança Digital',
      cnpj: '78.901.234/0001-56',
      email: 'soc@cybershield.security',
      phone: '(61) 3105-8800',
      contactName: 'Gabriel Nogueira (CISO)',
      companyType: 'Segurança da Informação',
      companyIndustry: 'Cybersecurity / Defesa Digital',
      segment: 'Cybersecurity & Defesa',
      companySize: '51–200 funcionários',
      city: 'Brasília',
      state: 'DF',
      country: 'Brasil',
      website: 'https://cybershield.security',
      description: 'Consultoria de alta complexidade em Blue Team, Red Team, auditorias SOC 2 e resposta a incidentes críticos.',
      logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
      jobsCount: 3,
      candidatesCount: 19,
      partnershipStatus: 'Ativa',
      createdAt: '2026-07-14T08:50:00Z',
    }
  },
  {
    id: 'emp_logiflow_08',
    name: 'LogiFlow Logística Inteligente',
    email: 'inovacao@logiflow.com.br',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'LogiFlow Logística Inteligente',
    companyData: {
      id: 'emp_logiflow_08',
      name: 'LogiFlow Logística Inteligente',
      cnpj: '89.012.345/0001-67',
      email: 'inovacao@logiflow.com.br',
      phone: '(81) 3099-1234',
      contactName: 'Tiago Albuquerque (Head de Produto)',
      companyType: 'Logística & Supply Chain',
      companyIndustry: 'LogTech / Cadeia de Suprimentos',
      segment: 'LogTech & Supply Chain',
      companySize: '201–500 funcionários',
      city: 'Recife',
      state: 'PE',
      country: 'Brasil',
      website: 'https://logiflow.com.br',
      description: 'Otimização algorítmica de frotas e roteirização com IoT e rastreamento em tempo real para grandes cadeias industriais.',
      logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=120&auto=format&fit=crop&q=80',
      jobsCount: 4,
      candidatesCount: 31,
      partnershipStatus: 'Ativa',
      createdAt: '2026-08-22T15:10:00Z',
    }
  },
  {
    id: 'emp_edupulse_09',
    name: 'EduPulse Tech & Learning',
    email: 'carreiras@edupulse.io',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'EduPulse Tech & Learning',
    companyData: {
      id: 'emp_edupulse_09',
      name: 'EduPulse Tech & Learning',
      cnpj: '90.123.456/0001-78',
      email: 'carreiras@edupulse.io',
      phone: '(48) 3211-5500',
      contactName: 'Patricia Duarte (Head de Pessoas)',
      companyType: 'Educação Digital & EdTech',
      companyIndustry: 'EdTech / Educação Corporativa',
      segment: 'EdTech & Learning',
      companySize: '51–200 funcionários',
      city: 'Florianópolis',
      state: 'SC',
      country: 'Brasil',
      website: 'https://edupulse.io',
      description: 'Plataforma de ensino adaptativo baseada em IA para requalificação técnica de engenheiros e cientistas de dados.',
      logo: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=120&auto=format&fit=crop&q=80',
      jobsCount: 3,
      candidatesCount: 24,
      partnershipStatus: 'Parceiro Premium',
      createdAt: '2026-08-28T09:30:00Z',
    }
  },
  {
    id: 'emp_agrosmart_10',
    name: 'AgroSmart Conectividade & IoT',
    email: 'talentos@agrosmart.agr.br',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'AgroSmart Conectividade & IoT',
    companyData: {
      id: 'emp_agrosmart_10',
      name: 'AgroSmart Conectividade & IoT',
      cnpj: '01.234.567/0001-89',
      email: 'talentos@agrosmart.agr.br',
      phone: '(16) 3600-4411',
      contactName: 'Marcos Vinicius (Diretor de P&D)',
      companyType: 'AgTech & IoT Rural',
      companyIndustry: 'Agricultura Digital / IoT',
      segment: 'AgTech & Automação Rural',
      companySize: '201–500 funcionários',
      city: 'Ribeirão Preto',
      state: 'SP',
      country: 'Brasil',
      website: 'https://agrosmart.agr.br',
      description: 'Sensores IoT de precisão, telemetria climática e algoritmos de previsão de safra conectados via satélite e redes privadas 5G.',
      logo: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=120&auto=format&fit=crop&q=80',
      jobsCount: 4,
      candidatesCount: 27,
      partnershipStatus: 'Ativa',
      createdAt: '2026-09-02T14:15:00Z',
    }
  },
  {
    id: 'emp_nexusgames_11',
    name: 'Nexus Game Studios',
    email: 'recrutamento@nexusgames.com',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'Nexus Game Studios',
    companyData: {
      id: 'emp_nexusgames_11',
      name: 'Nexus Game Studios',
      cnpj: '12.987.654/0001-90',
      email: 'recrutamento@nexusgames.com',
      phone: '(41) 3302-8877',
      contactName: 'Guilherme Toledo (Lead Producer)',
      companyType: 'Jogos Digitais & Unreal Engine',
      companyIndustry: 'Game Development / VR & 3D',
      segment: 'GameDev & Computação Gráfica',
      companySize: '51–200 funcionários',
      city: 'Curitiba',
      state: 'PR',
      country: 'Brasil',
      website: 'https://nexusgames.com',
      description: 'Estúdio independente focado em títulos multiplayer multiplataforma em Unreal Engine 5 e arquitetura de servidores de baixa latência.',
      logo: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=120&auto=format&fit=crop&q=80',
      jobsCount: 5,
      candidatesCount: 41,
      partnershipStatus: 'Estratégico',
      createdAt: '2026-09-10T11:45:00Z',
    }
  },
  {
    id: 'emp_segurodigital_12',
    name: 'SeguroDigital InsurTech',
    email: 'gente@segurodigital.com.br',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'SeguroDigital InsurTech',
    companyData: {
      id: 'emp_segurodigital_12',
      name: 'SeguroDigital InsurTech',
      cnpj: '23.876.543/0001-01',
      email: 'gente@segurodigital.com.br',
      phone: '(21) 3890-1122',
      contactName: 'Fernanda Albuquerque (People Partner)',
      companyType: 'InsurTech & Seguros Digitais',
      companyIndustry: 'Serviços de Seguros / InsurTech',
      segment: 'InsurTech & Seguros Digitais',
      companySize: '201–500 funcionários',
      city: 'Rio de Janeiro',
      state: 'RJ',
      country: 'Brasil',
      website: 'https://segurodigital.com.br',
      description: 'Cotação instantânea e apólices on-demand com modelos atuariais preditivos e antifraude baseados em inteligência artificial.',
      logo: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=120&auto=format&fit=crop&q=80',
      jobsCount: 3,
      candidatesCount: 20,
      partnershipStatus: 'Ativa',
      createdAt: '2026-09-15T16:00:00Z',
    }
  },
  {
    id: 'emp_ecogrid_13',
    name: 'EcoGrid Energia Inteligente',
    email: 'carreiras@ecogrid.energy',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'EcoGrid Energia Inteligente',
    companyData: {
      id: 'emp_ecogrid_13',
      name: 'EcoGrid Energia Inteligente',
      cnpj: '34.765.432/0001-12',
      email: 'carreiras@ecogrid.energy',
      phone: '(31) 3277-9900',
      contactName: 'Renato Sampaio (CTO)',
      companyType: 'CleanTech & Energia Solar',
      companyIndustry: 'CleanTech / Transição Energética',
      segment: 'CleanTech & Energia Renovável',
      companySize: '51–200 funcionários',
      city: 'Belo Horizonte',
      state: 'MG',
      country: 'Brasil',
      website: 'https://ecogrid.energy',
      description: 'Gestão inteligente de microrredes solares e eólicas com algoritmos de despacho econômico e balanceamento de carga em tempo real.',
      logo: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=120&auto=format&fit=crop&q=80',
      jobsCount: 4,
      candidatesCount: 28,
      partnershipStatus: 'Parceiro Premium',
      createdAt: '2026-09-20T10:30:00Z',
    }
  },
  {
    id: 'emp_saasify_14',
    name: 'SaaSify Plataformas B2B',
    email: 'talentos@saasify.cloud',
    role: 'Empresa',
    tipoUsuario: 'empresa',
    company: 'SaaSify Plataformas B2B',
    companyData: {
      id: 'emp_saasify_14',
      name: 'SaaSify Plataformas B2B',
      cnpj: '45.654.321/0001-23',
      email: 'talentos@saasify.cloud',
      phone: '(47) 3451-2233',
      contactName: 'Helena Castro (Talent Acquisition Lead)',
      companyType: 'Software as a Service (SaaS)',
      companyIndustry: 'Enterprise Software / Cloud B2B',
      segment: 'Enterprise SaaS & B2B',
      companySize: '500+ funcionários',
      city: 'Joinville',
      state: 'SC',
      country: 'Brasil',
      website: 'https://saasify.cloud',
      description: 'Plataforma multi-tenant de gestão corporativa e integração ERP utilizada por mais de 10.000 empresas em toda a América Latina.',
      logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=120&auto=format&fit=crop&q=80',
      jobsCount: 6,
      candidatesCount: 52,
      partnershipStatus: 'Ativa',
      createdAt: '2026-09-25T13:20:00Z',
    }
  }
];

export const INITIAL_PLANS: Plan[] = [
  {
    id: 'plano-starter',
    name: 'Plano Starter',
    description: 'Ideal para startups e empresas iniciando processos seletivos técnicos.',
    price: 199.00,
    period: 'mês',
    features: [
      'Acesso ao Algoritmo de Smart Matching',
      'Até 3 Vagas Ativas simultâneas',
      'Visualização de até 20 Candidatos por Vaga',
      'Relatório de Pontuação Aritmética (RG04)',
      'Suporte via E-mail',
    ],
    maxJobs: 3,
    maxMatches: 20,
    status: 'active',
    badge: 'Essencial',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'plano-pro',
    name: 'Plano Profissional',
    description: 'Para empresas em expansão que exigem contratações ágeis com triagem precisa.',
    price: 499.00,
    period: 'mês',
    features: [
      'Acesso Ilimitado a Smart Matching & Rankings',
      'Até 10 Vagas Ativas simultâneas',
      'Candidatos Ranqueados Ilimitados',
      'Detalhamento Completo de Competências Ponderadas',
      'Emissão de Pareceres e Gestão de Status',
      'Exportação de Relatórios de Triagem',
      'Suporte Prioritário por Chat & WhatsApp',
    ],
    maxJobs: 10,
    maxMatches: -1,
    status: 'active',
    isPopular: true,
    badge: 'Mais Recomendado',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'plano-enterprise',
    name: 'Plano Enterprise',
    description: 'Para grandes corporações e tech hubs com alta demanda de recrutamento especializado.',
    price: 999.00,
    period: 'mês',
    features: [
      'Vagas Ilimitadas & Matchings Ilimitados',
      'Trilha de Auditoria & Conformidade Completa (RG10)',
      'Acesso Direto a Currículos Sanitizados (RG01)',
      'Gestão Multi-recrutadores & Permissões',
      'Integração via Webhooks & API ATS',
      'Gerente de Conta & Treinamento Dedicado',
      'SLA de Atendimento Garantido em 1h',
    ],
    maxJobs: -1,
    maxMatches: -1,
    status: 'active',
    badge: 'Corporativo',
    createdAt: '2026-01-10T10:00:00Z',
  },
];

